### ISSUE TITLE
In labels file, use the original form of the label (e.g. `acl:relcl`, `nmod:poss`) instead of the one without colon

### ISSUE THREAD

**Issue by inariksit** [nltkgf/spacyconlltree#2]
Currently returns:

```
#fun root_nsubj_cop_aclRelcl head nsubj  cop  aclRelcl
```

Desired outcome:

```
#fun root_nsubj_cop_aclRelcl head nsubj  cop  acl:relcl 
```

**Comment by 1Regina** [comment]
fix the element back to UD format in Labels after "head" but retain format in fun 

`#fun root_nsubjPass_auxPass_advmod_advcl head nsubj:pass  aux:pass  advmod  advcl`

**Comment by 1Regina** [comment]
fix the element back to UD format in Labels after "head" but retain format in fun

`#fun root_nsubjPass_auxPass_advmod_advcl head nsubj:pass aux:pass advmod advcl`

**Comment by inariksit** [comment]
After the new feature in #4 , I see that the generated labels file has again labels without the colons.

For more instructions regarding labels file, I'll open a new issue.
